from app.ml.config import (
    MODELS_CONFIG,
    DISEASES_INFO,
    INFERENCE_CONFIG,
    BOX_COLORS,
    MODEL_ARCH_YOLO,
    MODEL_ARCH_DETR,
    get_model_config,
    get_model_arch,
    get_model_name_by_kind,
    get_kind_by_model_name,
    get_classes,
    get_labels,
    get_input_size,
    get_inference_config,
    get_box_color,
    get_all_model_keys,
    get_config_by_model_name,
)
from app.ml import tracker_config